#-------------------------------
# General Site Settings
title: 'AI Calculator: Calculate Anything with AI'
logo: '/images/Logo-calc.webp'
description:  "AI Calculator is a web application, here you can perform various calculations using different AI Calculators."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ai-calculator.github.io" # the base hostname & protocol for your site, e.g. http://example.com
blog-theme: light # By default, Atega theme uses a 'light' color scheme, to change the color scheme to dark use 'dark' value (_includes/color-scheme)

 
#-------------------------------
# Author Settings
author:
  name: Emily Stark
  image: '/images/Emily-Stark.webp' # Add your author image
  description: "I am a content writer and SEO specialist with a passion for artificial intelligence. I create engaging and informative content that helps businesses connect with their audience and achieve their goals."
  social:
    twitter: https://twitter.com/Emily-Stark


#-------------------------------
# Hero Settings
hero:
  hero__title: Calculate Anything with <span class="hero__name">AI Calculator</span>.
  hero__job: 
  hero__description: "AI Calculator is a web application, here you can perform various calculations using different AI Calculators."
  hero__button__text: Read about the Author # Add your button text
  hero__button__link: '/about'
  hero__image: '/images/hero-image.webp'


#-------------------------------
# Newsletter (_includes/footer-widgets/widget-subscribe.html)
# mailchimp__title: Subscribe to new posts # Add your Title
# mailchimp__text: Subscribe to our newsletter and weâ€™ll send you the emails of latest posts. # Add your description.
# mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
# mailchimp__button__text: Subscribe # Add your button text


#-------------------------------
# Contact Settings
contact:
  email: ai.calculate@gmail.com # Add your email for contant form
  description: If you are interested to talk, just shoot me a message

# NOTE
# Atega comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Social Links (Footer)
# Example of adding a new link to the footer - {icon: "ion-logo-facebook", link: "https://facebook.com"}
# Other icons can be found at https://ionicons.com/v4/
social:
# - {icon: "ion-logo-twitter", link: "https://twitter.com/posadchyi"}
- {icon: "ion-logo-github", link: "https://github.com/ai-calculator"}
# - {icon: "ion-logo-youtube", link: "https://youtube.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
# - {icon: "ion-logo-codepen", link: "https://codepen.io"}
# - {icon: "ion-logo-vimeo", link: "https://vimeo.com/"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier:  # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Gallery Footer Section
# gallery:
#   title: Gallery
#   images:
#     - alt: 'Minimalism'
#       url: '/images/landscape1.jpg'
#     - alt: 'Minimalism'
#       url: '/images/sasha1.jpeg'
#     - alt: 'Minimalism'
#       url: '/images/castle1.jpg'
#     - alt: 'Minimalism'
#       url: '/images/scotland1.jpg'
#     - alt: 'Minimalism'
#       url: '/images/sanfran1.jpg'
#     - alt: 'Minimalism'
#       url: '/images/newyork1.jpg'


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  /:title

sass:
  sass_dir: _sass
  style: compressed
